// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_O_6O-UlRngSxldwuufUEK7yy2ODP0SI',
    appId: '1:974603432903:web:21c9756c16e8ba287f9fe2',
    messagingSenderId: '974603432903',
    projectId: 'fluttergdgdemoapp',
    authDomain: 'fluttergdgdemoapp.firebaseapp.com',
    storageBucket: 'fluttergdgdemoapp.firebasestorage.app',
    measurementId: 'G-FPB2K2XNZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8RwzVbI89aRmK_1LZRNj3DdVDGTPI0ro',
    appId: '1:974603432903:android:8fb319b6764eeced7f9fe2',
    messagingSenderId: '974603432903',
    projectId: 'fluttergdgdemoapp',
    storageBucket: 'fluttergdgdemoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTFVY5g0KZ-3En6LOKXSKsAhzxP1oaqw',
    appId: '1:974603432903:ios:88bf4a378b7ed8dc7f9fe2',
    messagingSenderId: '974603432903',
    projectId: 'fluttergdgdemoapp',
    storageBucket: 'fluttergdgdemoapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterLivePollingGcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbTFVY5g0KZ-3En6LOKXSKsAhzxP1oaqw',
    appId: '1:974603432903:ios:88bf4a378b7ed8dc7f9fe2',
    messagingSenderId: '974603432903',
    projectId: 'fluttergdgdemoapp',
    storageBucket: 'fluttergdgdemoapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterLivePollingGcp',
  );
}
